// Re-export all types

// Re-export useQueryClient for contexts that need access to cache
export { useQueryClient } from '@tanstack/react-query';
export {
  isLayoutAgent,
  parseAgentSlug,
  resolveAgentName,
} from './agentResolver';
export type { InvokeOptions } from './api';
// Re-export utility functions
export {
  _setApiBase,
  _setLayoutContext,
  addProjectLayoutFromPlugin,
  bulkDeleteKnowledgeDocs,
  callTool,
  createChatSession,
  deleteKnowledgeDoc,
  fetchAvailableLayouts,
  fetchConfig,
  fetchKnowledgeDocContent,
  fetchKnowledgeDocs,
  fetchKnowledgeFiltered,
  fetchKnowledgeNamespaces,
  fetchKnowledgeStatus,
  fetchKnowledgeTree,
  fetchProjectConversations,
  invoke,
  invokeAgent,
  scanKnowledgeDirectory,
  searchKnowledge,
  sendMessage,
  streamMessage,
  updateKnowledgeDoc,
  updateKnowledgeNamespace,
  uploadKnowledge,
} from './api';
export type { AutoSelectItem } from './components';
// Re-export components
export {
  ActionButton,
  AuthStatusBadge,
  AutoSelectModal,
  Button,
  FullScreenError,
  FullScreenLoader,
  LayoutHeader,
  LoadingState,
  Pill,
  Spinner,
} from './components';
export { contextRegistry } from './context/registry.js';
export type {
  ContextCapability,
  MessageContextProvider,
} from './context/types.js';
// Core utilities
export { ListenerManager, noopSubscribe } from './core/ListenerManager.js';
// Re-export context hooks
export {
  useActiveChatActions,
  useActiveChatState,
  useAgent,
  // Agent management
  useAgents,
  // Configuration
  useApiBase,
  useAuth,
  useAvailableModels,
  useConfig,
  useConversation,
  useConversationMessages,
  useConversationStats,
  // Conversation management
  useConversations,
  // Chat operations
  useCreateChatSession,
  useDockState,
  // Keyboard shortcuts
  useKeyboardShortcut,
  useKeyboardShortcuts,
  useKnowledgeDocs,
  useKnowledgeNamespaces,
  useKnowledgeSearch,
  // Chat utilities
  useLaunchChat,
  useLayout,
  // Layout management
  useLayouts,
  // Models
  useModels,
  // Navigation
  useNavigation,
  // Notifications
  useNotifications,
  useOpenConversation,
  useProject,
  // Project management
  useProjects,
  useResolveAgent,
  // SDK access
  useSDK,
  useSendMessage,
  useSendToChat,
  // Server-side fetch proxy
  useServerFetch,
  // Slash commands
  useSlashCommandHandler,
  useSlashCommands,
  // Statistics
  useStats,
  // Toast notifications
  useToast,
  // Tool approval
  useToolApproval,
  // User directory
  useUserLookup,
  useWorkflowFiles,
  // Workflows
  useWorkflows,
} from './hooks';
// Re-export layout utilities
export { createLayoutContext } from './layout/context';
export type { ProviderMetadata } from './layoutProviders';
// Re-export layout provider hooks (delegates to core app)
export {
  _setProviderFunctions,
  configureProvider,
  getActiveProviderId,
  getProvider,
  hasProvider,
  registerProvider,
} from './layoutProviders';
export { NotificationsAPI } from './notifications/index.js';
// Re-export components
export {
  LayoutNavigationProvider,
  LayoutProvider,
  SDKContext,
  SDKProvider,
  useLayoutNavigation,
} from './providers';
export {
  type ACPConnectionInfo,
  type AcpSlashCommandDescriptor,
  type AgentHealthStatus,
  type AgentTemplate,
  type AuthStatusData,
  type AvailableProjectLayout,
  analyzeFeedback,
  type BrandingData,
  type CodingFileEntry,
  type ConnectionMutationInput,
  type ConnectionTestResult,
  type ConversationLookup,
  type ConversationMessage,
  type ConversationMessagePart,
  type ConversationSummary,
  type CoreUpdateStatus,
  clearFeedbackAnalysis,
  createACPConnection,
  createAgent,
  createVoiceSession,
  deleteACPConnection,
  deleteAgent,
  deleteConversation,
  deleteFeedbackRating,
  dispatchOrchestrationCommand,
  executeCodingCommand,
  type FileSystemBrowseEntry,
  type FileSystemBrowseResult,
  fetchACPConnections,
  fetchAcpCommandOptions,
  fetchAcpCommands,
  fetchAgentConversations,
  fetchAuthStatus,
  fetchBranding,
  fetchCodingDiff,
  fetchCodingFileContent,
  fetchCodingFiles,
  fetchConversationById,
  fetchConversationMessages,
  fetchFeedbackRatings,
  fetchInsights,
  fetchMonitoringEvents,
  fetchMonitoringMetrics,
  fetchMonitoringStats,
  fetchNotifications,
  fetchOrchestrationProviders,
  fetchPromptById,
  fetchTerminalPort,
  fetchUsageStats,
  fetchVapidPublicKey,
  type GlobalKnowledgeStatus,
  type IntegrationViewModel,
  type MonitoringAgentStat,
  type MonitoringMetric,
  type MonitoringStatsData,
  type OrchestrationCommandInput,
  type OrchestrationProviderSummary,
  type PluginChangelogData,
  type PluginChangelogEntry,
  type PluginProviderDetail,
  type PluginSettingField,
  type PluginSettingsData,
  type RegistryCatalogTab,
  reconnectACPConnection,
  reloadPlugins,
  renameConversation,
  renewAuth,
  rescanAnalytics,
  resetUsageStats,
  resolveOrchestrationRequest,
  type ServerCapabilities,
  type SystemPrerequisite,
  type SystemStatus,
  sendOrchestrationTurn,
  startOrchestrationSession,
  streamConversationTurn,
  submitToolApproval,
  subscribePushNotifications,
  unsubscribePushNotifications,
  updateACPConnection,
  updateAgent,
  useACPConnectionsQuery,
  useAchievementsQuery,
  useAcpCommandsQuery,
  useActivityUsageQuery,
  useAddJob,
  useAddLayoutFromPluginMutation,
  useAddProjectLayoutFromPluginMutation,
  useAgentInvokeMutation,
  useAgentQuery,
  useAgentsQuery,
  useAgentTemplatesQuery,
  useAgentToolsQuery,
  useAgentWorkflowsQuery,
  useAnalyticsRescanMutation,
  useAnalyzeFeedbackMutation,
  useApplyCoreUpdateMutation,
  useAuthStatusQuery,
  useAvailableProjectLayoutsQuery,
  useBrandingQuery,
  useClearFeedbackAnalysisMutation,
  useClearNotificationsMutation,
  useCodingDiffQuery,
  useCodingFileContentQuery,
  useCodingFilesQuery,
  useConfigQuery,
  useConnectionQuery,
  useConnectionsQuery,
  useConversationsQuery,
  useCoreUpdateStatusQuery,
  useCreateACPConnectionMutation,
  useCreateAgentMutation,
  useCreateLayoutMutation,
  useCreatePlaybookMutation,
  useCreateProjectLayoutMutation,
  useCreateProjectMutation,
  useCreateWorkflowMutation,
  useDeleteACPConnectionMutation,
  useDeleteAgentMutation,
  useDeleteConnectionMutation,
  useDeleteConversationMutation,
  useDeleteFeedbackRatingMutation,
  useDeleteIntegrationMutation,
  useDeleteJob,
  useDeletePlaybookMutation,
  useDeleteProjectLayoutMutation,
  useDeleteProjectMutation,
  useDeleteWorkflowMutation,
  useDismissNotificationMutation,
  useEditJob,
  useFeedbackGuidelinesQuery,
  useFeedbackRatingsQuery,
  useFeedbackStatusQuery,
  useFetchRunOutput,
  useFileSystemBrowseQuery,
  useGitLogQuery,
  useGitStatusQuery,
  useGlobalKnowledgeStatusQuery,
  useImportPlaybooksMutation,
  useInsightsQuery,
  useInstalledRegistryItemsQuery,
  useInstallSkillMutation,
  useIntegrationQuery,
  useIntegrationsQuery,
  useInvokeAgent,
  useJobLogs,
  useKnowledgeBulkDeleteMutation,
  useKnowledgeDeleteMutation,
  useKnowledgeDocContentQuery,
  useKnowledgeDocsQuery,
  useKnowledgeFilteredQuery,
  useKnowledgeNamespacesQuery,
  useKnowledgeSaveMutation,
  useKnowledgeScanMutation,
  useKnowledgeSearchQuery,
  useKnowledgeStatusQuery,
  useKnowledgeTreeQuery,
  useKnowledgeUpdateMutation,
  useModelCapabilitiesQuery,
  useModelConnectionsQuery,
  useModelsQuery,
  useMonitoringMetricsQuery,
  useMonitoringStatsQuery,
  useNotificationActionMutation,
  useNotificationsQuery,
  useOpenArtifact,
  useOrchestrationProvidersQuery,
  usePlaybooksQuery,
  usePluginChangelogQuery,
  usePluginInstallMutation,
  usePluginPreviewMutation,
  usePluginProvidersQuery,
  usePluginProviderToggleMutation,
  usePluginRegistryInstallMutation,
  usePluginRemoveMutation,
  usePluginSettingsMutation,
  usePluginSettingsQuery,
  usePluginsQuery,
  usePluginUpdateMutation,
  usePluginUpdatesQuery,
  usePreviewSchedule,
  useProjectConversationsQuery,
  useProjectLayoutQuery,
  useProjectLayoutsQuery,
  useProjectQuery,
  useProjectsQuery,
  usePromptQuery,
  usePromptsQuery,
  useReconnectACPConnectionMutation,
  useReconnectIntegrationMutation,
  useRecordPlaybookOutcomeMutation,
  useRegistryAgentActionMutation,
  useRegistryIntegrationActionMutation,
  useRegistryIntegrationsQuery,
  useRegistryItemsQuery,
  useRegistryPluginsQuery,
  useRegistrySkillActionMutation,
  useRegistrySkillsQuery,
  useReloadPluginsMutation,
  useRenameConversationMutation,
  useRenewAuthMutation,
  useResetUsageStatsMutation,
  useRunJob,
  useRuntimeConnectionsQuery,
  useSaveConnectionMutation,
  useSaveFeedbackRatingMutation,
  useSaveIntegrationMutation,
  useSchedulerJobs,
  useSchedulerProviders,
  useSchedulerStats,
  useSchedulerStatus,
  useServerCapabilitiesQuery,
  useSkillContentQuery,
  useSkillsQuery,
  useStatsQuery,
  useSystemStatusForApiBaseQuery,
  useSystemStatusQuery,
  useTemplatesQuery,
  useTestConnectionMutation,
  useTestVectorDbConnectionMutation,
  useToggleJob,
  useTrackPlaybookRunMutation,
  useUninstallSkillMutation,
  useUpdateACPConnectionMutation,
  useUpdateAgentMutation,
  useUpdateConfigMutation,
  useUpdatePlaybookMutation,
  useUpdateProjectMutation,
  useUpdateSkillMutation,
  useUpdateWorkflowMutation,
  useUsageQuery,
  useUserQuery,
  useVerifyBedrockMutation,
  useWorkflowContentQuery,
  verifyBedrockConnection,
  type WorkflowFile,
  waitForAgentHealth,
} from './queries';
// Re-export query hooks (plugins use these instead of raw React Query)
export {
  type MutationOptions,
  type QueryConfig,
  resolveApiBase,
  useApiMutation,
  useApiQuery,
  useInvalidateQuery,
} from './query-core';
// Re-export query factories (for imperative fetching in commands)
export {
  agentQueries,
  conversationQueries,
  knowledgeQueries,
  orchestrationQueries,
} from './queryFactories';
export { telemetry } from './telemetry';
export * from './types';
export { voiceRegistry } from './voice/registry.js';
// Voice + context provider interfaces and registries
export type {
  ConversationalOptions,
  ConversationalSessionState,
  ConversationalVoiceProvider,
  ProviderCapability,
  STTOptions,
  STTProvider,
  STTState,
  TTSOptions,
  TTSProvider,
  VisibleOn,
} from './voice/types.js';
