/**
 * SDK Query Hooks - Wraps React Query for API calls
 * Plugins use these instead of raw useQuery
 */

export {
  type ACPConnectionInfo,
  type AcpSlashCommandDescriptor,
  createACPConnection,
  deleteACPConnection,
  type FileSystemBrowseEntry,
  type FileSystemBrowseResult,
  fetchACPConnections,
  fetchAcpCommandOptions,
  fetchAcpCommands,
  fetchPromptById,
  reconnectACPConnection,
  updateACPConnection,
  useACPConnectionsQuery,
  useAcpCommandsQuery,
  useCreateACPConnectionMutation,
  useDeleteACPConnectionMutation,
  useFileSystemBrowseQuery,
  usePromptQuery,
  useReconnectACPConnectionMutation,
  useTemplatesQuery,
  useUpdateACPConnectionMutation,
} from './query-domains/acpWorkspace';
export {
  type AgentTemplate,
  createAgent,
  deleteAgent,
  submitToolApproval,
  updateAgent,
  useAgentQuery,
  useAgentsQuery,
  useAgentTemplatesQuery,
  useAgentToolsQuery,
  useConfigQuery,
  useCreateAgentMutation,
  useDeleteAgentMutation,
  useModelCapabilitiesQuery,
  useModelsQuery,
  useStatsQuery,
  useUpdateAgentMutation,
  useUpdateConfigMutation,
  useUserQuery,
} from './query-domains/agentAdmin';
export {
  analyzeFeedback,
  clearFeedbackAnalysis,
  deleteFeedbackRating,
  type FeedbackRatingDeleteInput,
  type FeedbackRatingInput,
  fetchFeedbackRatings,
  fetchInsights,
  fetchUsageStats,
  rescanAnalytics,
  resetUsageStats,
  saveFeedbackRating,
  useAchievementsQuery,
  useActivityUsageQuery,
  useAnalyticsRescanMutation,
  useAnalyzeFeedbackMutation,
  useClearFeedbackAnalysisMutation,
  useDeleteFeedbackRatingMutation,
  useFeedbackGuidelinesQuery,
  useFeedbackRatingsQuery,
  useFeedbackStatusQuery,
  useInsightsQuery,
  useResetUsageStatsMutation,
  useSaveFeedbackRatingMutation,
  useUsageQuery,
} from './query-domains/analytics';
export {
  type IntegrationViewModel,
  type RegistryCatalogTab,
  useCreatePlaybookMutation,
  useDeleteIntegrationMutation,
  useDeletePlaybookMutation,
  useImportPlaybooksMutation,
  useInstalledRegistryItemsQuery,
  useIntegrationQuery,
  useIntegrationsQuery,
  usePlaybooksQuery,
  usePromptsQuery,
  useReconnectIntegrationMutation,
  useRegistryAgentActionMutation,
  useRecordPlaybookOutcomeMutation,
  useRegistryIntegrationActionMutation,
  useRegistryIntegrationsQuery,
  useRegistryItemsQuery,
  useRegistrySkillActionMutation,
  useSaveIntegrationMutation,
  useTrackPlaybookRunMutation,
  useUpdatePlaybookMutation,
} from './query-domains/catalog';
export {
  type ChatAttachmentInput,
  type CodingFileEntry,
  type ConversationLookup,
  type ConversationMessage,
  type ConversationMessagePart,
  type ConversationSummary,
  createVoiceSession,
  deleteConversation,
  dispatchOrchestrationCommand,
  executeCodingCommand,
  fetchAgentConversations,
  fetchCodingDiff,
  fetchCodingFileContent,
  fetchCodingFiles,
  fetchConversationById,
  fetchConversationMessages,
  fetchOrchestrationProviders,
  fetchTerminalPort,
  fetchVapidPublicKey,
  type OrchestrationCommandInput,
  type OrchestrationProviderSummary,
  renameConversation,
  resolveOrchestrationRequest,
  sendOrchestrationTurn,
  startOrchestrationSession,
  streamConversationTurn,
  subscribePushNotifications,
  unsubscribePushNotifications,
  useCodingDiffQuery,
  useCodingFileContentQuery,
  useCodingFilesQuery,
  useConversationsQuery,
  useDeleteConversationMutation,
  useOrchestrationProvidersQuery,
  useRenameConversationMutation,
} from './query-domains/chatRuntime';
export {
  actOnNotification,
  clearNotifications,
  dismissNotification,
  fetchNotifications,
  useClearNotificationsMutation,
  useDismissNotificationMutation,
  useNotificationActionMutation,
  useNotificationsQuery,
} from './query-domains/notifications';
export {
  type AgentHealthStatus,
  type PluginChangelogData,
  type PluginChangelogEntry,
  type PluginProviderDetail,
  type PluginSettingField,
  type PluginSettingsData,
  reloadPlugins,
  requestAgentHealth,
  useAddLayoutFromPluginMutation,
  useAddProjectLayoutFromPluginMutation,
  usePluginChangelogQuery,
  usePluginInstallMutation,
  usePluginPreviewMutation,
  usePluginProvidersQuery,
  usePluginProviderToggleMutation,
  usePluginRegistryInstallMutation,
  usePluginRemoveMutation,
  usePluginSettingsMutation,
  usePluginSettingsQuery,
  usePluginsQuery,
  usePluginUpdateMutation,
  usePluginUpdatesQuery,
  useRegistryPluginsQuery,
  useReloadPluginsMutation,
  waitForAgentHealth,
} from './query-domains/plugins';
export {
  useGitLogQuery,
  useGitStatusQuery,
  useKnowledgeBulkDeleteMutation,
  useKnowledgeDeleteMutation,
  useKnowledgeDocContentQuery,
  useKnowledgeDocsQuery,
  useKnowledgeFilteredQuery,
  useKnowledgeNamespacesQuery,
  useKnowledgeSaveMutation,
  useKnowledgeScanMutation,
  useKnowledgeSearchQuery,
  useKnowledgeStatusQuery,
  useKnowledgeTreeQuery,
  useKnowledgeUpdateMutation,
  useProjectConversationsQuery,
} from './query-domains/projectData';
export {
  useAddJob,
  useDeleteJob,
  useEditJob,
  useFetchRunOutput,
  useJobLogs,
  useOpenArtifact,
  usePreviewSchedule,
  useRunJob,
  useSchedulerJobs,
  useSchedulerProviders,
  useSchedulerStats,
  useSchedulerStatus,
  useToggleJob,
} from './query-domains/scheduler';
export {
  useInstallSkillMutation,
  useRegistrySkillsQuery,
  useSkillContentQuery,
  useSkillsQuery,
  useUninstallSkillMutation,
  useUpdateSkillMutation,
} from './query-domains/skills';
export {
  type AuthStatusData,
  type BrandingData,
  type CoreUpdateStatus,
  fetchAuthStatus,
  fetchBranding,
  fetchMonitoringEvents,
  fetchMonitoringMetrics,
  fetchMonitoringStats,
  type MonitoringAgentStat,
  type MonitoringMetric,
  type MonitoringStatsData,
  renewAuth,
  type ServerCapabilities,
  type SystemPrerequisite,
  type SystemStatus,
  useApplyCoreUpdateMutation,
  useAuthStatusQuery,
  useBrandingQuery,
  useCoreUpdateStatusQuery,
  useMonitoringMetricsQuery,
  useMonitoringStatsQuery,
  useRenewAuthMutation,
  useServerCapabilitiesQuery,
  useSystemStatusForApiBaseQuery,
  useSystemStatusQuery,
  useVerifyBedrockMutation,
  verifyBedrockConnection,
} from './query-domains/systemRuntime';
export {
  type AvailableProjectLayout,
  type ConnectionMutationInput,
  type ConnectionTestResult,
  type GlobalKnowledgeStatus,
  useAgentInvokeMutation,
  useAgentWorkflowsQuery,
  useAvailableProjectLayoutsQuery,
  useConnectionQuery,
  useConnectionsQuery,
  useCreateLayoutMutation,
  useCreateProjectLayoutMutation,
  useCreateProjectMutation,
  useCreateWorkflowMutation,
  useDeleteConnectionMutation,
  useDeleteProjectLayoutMutation,
  useDeleteProjectMutation,
  useDeleteWorkflowMutation,
  useGlobalKnowledgeStatusQuery,
  useInvokeAgent,
  useModelConnectionsQuery,
  useProjectLayoutQuery,
  useProjectLayoutsQuery,
  useProjectQuery,
  useProjectsQuery,
  useRuntimeConnectionsQuery,
  useSaveConnectionMutation,
  useTestConnectionMutation,
  useTestVectorDbConnectionMutation,
  useUpdateProjectMutation,
  useUpdateWorkflowMutation,
  useWorkflowContentQuery,
  type WorkflowFile,
} from './query-domains/workspace';
