/**
 * SDK Query Hooks - Wraps React Query for API calls
 * Plugins use these instead of raw useQuery
 */
export {
  type AgentTemplate,
  createAgent,
  deleteAgent,
  submitToolApproval,
  updateAgent,
  useAgentQuery,
  useAgentTemplatesQuery,
  useAgentsQuery,
  useAgentToolsQuery,
  useConfigQuery,
  useCreateAgentMutation,
  useDeleteAgentMutation,
  useModelCapabilitiesQuery,
  useModelsQuery,
  useStatsQuery,
  useUpdateAgentMutation,
  useUpdateConfigMutation,
  useUserQuery,
} from './query-domains/agentAdmin';
export {
  type ChatAttachmentInput,
  type CodingFileEntry,
  type ConversationLookup,
  type ConversationMessage,
  type ConversationMessagePart,
  type ConversationSummary,
  type OrchestrationCommandInput,
  type OrchestrationProviderSummary,
  createVoiceSession,
  deleteConversation,
  dispatchOrchestrationCommand,
  executeCodingCommand,
  fetchAgentConversations,
  fetchCodingDiff,
  fetchCodingFileContent,
  fetchCodingFiles,
  fetchConversationById,
  fetchConversationMessages,
  fetchOrchestrationProviders,
  fetchTerminalPort,
  fetchVapidPublicKey,
  renameConversation,
  resolveOrchestrationRequest,
  sendOrchestrationTurn,
  startOrchestrationSession,
  streamConversationTurn,
  subscribePushNotifications,
  unsubscribePushNotifications,
  useCodingDiffQuery,
  useCodingFileContentQuery,
  useCodingFilesQuery,
  useConversationsQuery,
  useDeleteConversationMutation,
  useOrchestrationProvidersQuery,
  useRenameConversationMutation,
} from './query-domains/chatRuntime';
export {
  type ACPConnectionInfo,
  type AcpSlashCommandDescriptor,
  type FileSystemBrowseEntry,
  type FileSystemBrowseResult,
  createACPConnection,
  deleteACPConnection,
  fetchACPConnections,
  fetchAcpCommandOptions,
  fetchAcpCommands,
  fetchPromptById,
  reconnectACPConnection,
  updateACPConnection,
  useACPConnectionsQuery,
  useAcpCommandsQuery,
  useCreateACPConnectionMutation,
  useDeleteACPConnectionMutation,
  useFileSystemBrowseQuery,
  usePromptQuery,
  useReconnectACPConnectionMutation,
  useTemplatesQuery,
  useUpdateACPConnectionMutation,
} from './query-domains/acpWorkspace';
export {
  type IntegrationViewModel,
  type RegistryCatalogTab,
  useCreatePlaybookMutation,
  useDeleteIntegrationMutation,
  useDeletePlaybookMutation,
  useImportPlaybooksMutation,
  useInstalledRegistryItemsQuery,
  useIntegrationQuery,
  useIntegrationsQuery,
  usePlaybooksQuery,
  usePromptsQuery,
  useReconnectIntegrationMutation,
  useRegistryIntegrationActionMutation,
  useRegistryIntegrationsQuery,
  useRegistryItemsQuery,
  useSaveIntegrationMutation,
  useUpdatePlaybookMutation,
} from './query-domains/catalog';
export {
  type FeedbackRatingDeleteInput,
  type FeedbackRatingInput,
  analyzeFeedback,
  clearFeedbackAnalysis,
  deleteFeedbackRating,
  fetchFeedbackRatings,
  fetchInsights,
  fetchUsageStats,
  rescanAnalytics,
  resetUsageStats,
  saveFeedbackRating,
  useAchievementsQuery,
  useActivityUsageQuery,
  useAnalyticsRescanMutation,
  useAnalyzeFeedbackMutation,
  useClearFeedbackAnalysisMutation,
  useDeleteFeedbackRatingMutation,
  useFeedbackGuidelinesQuery,
  useFeedbackRatingsQuery,
  useFeedbackStatusQuery,
  useInsightsQuery,
  useResetUsageStatsMutation,
  useSaveFeedbackRatingMutation,
  useUsageQuery,
} from './query-domains/analytics';
export {
  type AuthStatusData,
  type BrandingData,
  type CoreUpdateStatus,
  type MonitoringAgentStat,
  type MonitoringMetric,
  type MonitoringStatsData,
  type ServerCapabilities,
  type SystemPrerequisite,
  type SystemStatus,
  fetchAuthStatus,
  fetchBranding,
  fetchMonitoringEvents,
  fetchMonitoringMetrics,
  fetchMonitoringStats,
  renewAuth,
  useApplyCoreUpdateMutation,
  useAuthStatusQuery,
  useBrandingQuery,
  useCoreUpdateStatusQuery,
  useMonitoringMetricsQuery,
  useMonitoringStatsQuery,
  useRenewAuthMutation,
  useServerCapabilitiesQuery,
  useSystemStatusForApiBaseQuery,
  useSystemStatusQuery,
  useVerifyBedrockMutation,
  verifyBedrockConnection,
} from './query-domains/systemRuntime';
export {
  type AgentHealthStatus,
  type PluginChangelogData,
  type PluginChangelogEntry,
  type PluginProviderDetail,
  type PluginSettingField,
  type PluginSettingsData,
  reloadPlugins,
  requestAgentHealth,
  useAddLayoutFromPluginMutation,
  useAddProjectLayoutFromPluginMutation,
  usePluginChangelogQuery,
  usePluginInstallMutation,
  usePluginPreviewMutation,
  usePluginProviderToggleMutation,
  usePluginProvidersQuery,
  usePluginRegistryInstallMutation,
  usePluginRemoveMutation,
  usePluginSettingsMutation,
  usePluginSettingsQuery,
  usePluginUpdateMutation,
  usePluginUpdatesQuery,
  usePluginsQuery,
  useRegistryPluginsQuery,
  useReloadPluginsMutation,
  waitForAgentHealth,
} from './query-domains/plugins';
export {
  useAddJob,
  useDeleteJob,
  useEditJob,
  useFetchRunOutput,
  useJobLogs,
  useOpenArtifact,
  usePreviewSchedule,
  useRunJob,
  useSchedulerJobs,
  useSchedulerProviders,
  useSchedulerStats,
  useSchedulerStatus,
  useToggleJob,
} from './query-domains/scheduler';
export {
  useInstallSkillMutation,
  useRegistrySkillsQuery,
  useSkillContentQuery,
  useSkillsQuery,
  useUninstallSkillMutation,
  useUpdateSkillMutation,
} from './query-domains/skills';
export {
  useGitLogQuery,
  useGitStatusQuery,
  useKnowledgeBulkDeleteMutation,
  useKnowledgeDeleteMutation,
  useKnowledgeDocContentQuery,
  useKnowledgeDocsQuery,
  useKnowledgeFilteredQuery,
  useKnowledgeNamespacesQuery,
  useKnowledgeSaveMutation,
  useKnowledgeScanMutation,
  useKnowledgeSearchQuery,
  useKnowledgeStatusQuery,
  useKnowledgeTreeQuery,
  useKnowledgeUpdateMutation,
  useProjectConversationsQuery,
} from './query-domains/projectData';
export {
  type AvailableProjectLayout,
  type ConnectionMutationInput,
  type ConnectionTestResult,
  type GlobalKnowledgeStatus,
  type WorkflowFile,
  useAgentInvokeMutation,
  useAgentWorkflowsQuery,
  useAvailableProjectLayoutsQuery,
  useConnectionQuery,
  useConnectionsQuery,
  useCreateLayoutMutation,
  useCreateProjectLayoutMutation,
  useCreateProjectMutation,
  useDeleteConnectionMutation,
  useDeleteProjectLayoutMutation,
  useDeleteProjectMutation,
  useGlobalKnowledgeStatusQuery,
  useInvokeAgent,
  useModelConnectionsQuery,
  useProjectLayoutQuery,
  useProjectLayoutsQuery,
  useProjectQuery,
  useProjectsQuery,
  useRuntimeConnectionsQuery,
  useSaveConnectionMutation,
  useTestConnectionMutation,
  useTestVectorDbConnectionMutation,
  useUpdateProjectMutation,
  useUpdateWorkflowMutation,
  useCreateWorkflowMutation,
  useDeleteWorkflowMutation,
  useWorkflowContentQuery,
} from './query-domains/workspace';
