version: 0.2

phases:
  install:
    commands:
      - choco install nodejs --version=20.18.0 -y --no-progress
      - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended" -y --no-progress
      - choco install rustup.install -y --no-progress
      - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") + ";$env:USERPROFILE\.cargo\bin"
  
  pre_build:
    commands:
      - node --version
      - rustc --version
      - cargo --version
      - npm install
  
  build:
    commands:
      - Set-Location packages/sdk; npm install; npm run build; Set-Location ../..
      - npm run build:desktop

artifacts:
  files:
    - 'src-desktop/target/release/bundle/**/*'
  name: tauri-windows-build
