version: 0.2

phases:
  install:
    commands:
      - choco install nodejs --version=20.18.0 -y --no-progress
      - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended" -y --no-progress
      - choco install rustup.install -y --no-progress
  
  pre_build:
    commands:
      - node --version
      - npm install
  
  build:
    commands:
      - Set-Location packages/sdk; npm install; npm run build; Set-Location ../..
      - cmd /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat`" && set PATH=C:\Users\ContainerAdministrator\.cargo\bin;%PATH% && npm run build:desktop"

artifacts:
  files:
    - 'src-desktop/target/release/bundle/**/*'
  name: tauri-windows-build
