// Read-only stallion-control tools safe for auto-approve.
export const SC_READ_ONLY_TOOLS = [
  'list_agents',
  'get_agent',
  'list_skills',
  'list_registry_skills',
  'list_integrations',
  'get_integration',
  'list_registry_integrations',
  'list_providers',
  'list_playbooks',
  'list_prompts',
  'list_jobs',
  'system_status',
  'list_models',
  'navigate_to',
  'list_projects',
  'get_project',
  'list_project_layouts',
  'list_layouts',
  'get_layout',
  'list_conversations',
  'get_conversation_messages',
  'get_config',
  'list_plugins',
  'check_plugin_updates',
  'get_usage',
  'get_achievements',
].map((toolName) => `stallion-control_${toolName}`);
